### ISSUE TITLE
Go Club in Albi, 81, France

### ISSUE THREAD

**Issue by xcombelle** [slashme/goclubdb#15]
Looks like there is a go club in Albi (but with no regular meeting) http://ffg.jeudego.org/php/afficheGroupe.php?idGroupe=330 why it is not on the map ?

**Comment by slashme** [comment]
Hi Xavier,

I probably missed that one. You can add it at http://goclubdb.herokuapp.com/club/FR/create if it has a fixed address.

Because I think you're cool, I've given you access to the repository: you don't need it to fix this bug, but it's always safer to have more people on a repo, and that way I can be cheeky and assign this to you ;-]

Thank you!

**Comment by xcombelle** [comment]
I did it http://goclubdb.herokuapp.com/club/45/
